workflows:
  ios-workflow:
    name: Build iOS IPA

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: co.median.ios.mpowaz   # <-- CHANGE THIS

    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
