name: freebrokery
description: Freebrokery WebView App
publish_to: 'none'

# Updated Version
version: 2.0.4+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.1
  permission_handler: ^12.0.1
  file_picker: ^10.3.10

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
